@Library('utils') _

pipeline {
  agent {
    kubernetes {
      label 'simple-pipeline'
      defaultContainer 'jnlp'
      yamlFile 'pods.yaml'
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
        container('busybox') {
          sh '/bin/busybox'
        }
      }
    }
    stage('Test shared library') {
    	steps {
    		container('busybox') {
    			notifySlack "Hello from shared library."
    		}
    	}
    }
  }
}
