@Library('utils') _

pipeline {
  agent {
    kubernetes {
      label 'flask-app'
      defaultContainer 'jnlp'
      yamlFile 'jenkins-manifests/docker.yaml'
    }
  }
  stages {
    stage('Build docker image') {
      steps {
        container('dind') {
          sh 'make docker-build'
        }
      }
    }
    stage('Lint') {
      steps {
        container('dind') {
          sh 'make lint'
        }
      }
    }
    stage('Test') {
      steps {
        container('dind') {
          sh 'make test'
        }
      }
    }
    stage('Test shared library') {
    	steps {
    		container('dind') {
    			notifySlack "Hello from shared library."
    		}
    	}
    }
  }
}
