apiVersion: v1
kind: Pod
metadata:
  labels:
    gh-jenkins-pod-type: busybox
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
